---
title: "Exam 01 review"
author: "Prof. Maria Tackett"
date: "2024-10-03"
date-format: "MMM DD, YYYY"
footer: "[🔗 STA 221 - Fall 2024](https://sta221-fa24.netlify.app)"
logo: "../images/logo.png"
format: 
  revealjs:
    theme: slides.scss
    multiplex: false
    transition: fade
    slide-number: true
    incremental: false 
    chalkboard: true
    include-before: [ '<script type="text/x-mathjax-config">MathJax.Hub.Config({tex2jax: {enableAssistiveMml: false}});</script>']
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
execute:
  freeze: auto
  echo: true
knitr:
  opts_chunk: 
    R.options:      
    width: 200
filters:
  - parse-latex
bibliography: references.bib
---

## Announcements {.midi}

-   Project Proposal due TODAY at 11:59pm

-   Lab 03 due TODAY at 11:59pm

-   HW 02 due TODAY at 11:59pm

-   Exam 01: Tuesday, October 8 (in class + take-home)

    -   Lecture recordings available until the start of the in-class exam (Link on side bar of webpage)

    -   Monday's lab: Exam office hours

    -   No office hours while take-home exam is out

## Exam 01 {.midi}

-   20s% of final course grade

-   50 points total <!--# UPDATE THIS-->

    -   in-class: 40 points
    -   take-home: 10 points

-   In-class: 75 minutes during Tuesday, October 8 lecture

-   Take-home:

    -   Released: Tuesday, October 8 \~ 1pm
    -   Due: Thursday, October 10 at 11:30 (we will have class Thursday)
    -   Similar in format to a lab/ HW

-   If you miss any part of the exam for an excused absence (with academic dean's note), your Exam 02 score will be counted twice

## Content: Weeks 1 - 6

::: columns
::: {.column width="50%"}
-   Exploratory data analysis

-   Fitting and interpreting linear regression models

-   Model assessment and comparison

-   ANOVA

-   Categorical + interaction terms
:::

::: {.column width="50%"}
-   Inference for model coefficients

-   Matrix representation of regression

-   Finding the least-squares estimator (no geometric interpretation)

-   Properties of the least-squares estimator
:::
:::

## Outline of in-class portion {.midi}

-   Closed-book, closed-note.

-   8 questions, some with multiple parts

-   Question types:

    -   Short answer (show work / explain response)
    -   True/ False.
        -   If false, write 1 - 2 sentence justification about why it is false.
    -   Derivations

-   Will be provided all relevant R output and a page of math rules <!--# Update link-->

-   Just need a pencil or pen. No calculator permitted on exam.

# Application exercise

::: appex
📋
:::

-   Sit with your lab group.

-   Put your group's response to your assigned exercise on Ed Discussion. <!--# update-->
