---
title: "Logistic Regression Review"
author: "Prof. Maria Tackett"
date: "2024-11-21"
date-format: "MMM DD, YYYY"
footer: "[🔗 STA 221 - Fall 2024](https://sta221-fa24.netlify.app)"
logo: "../images/logo.png"
format: 
  revealjs:
    theme: slides.scss
    multiplex: false
    transition: fade
    slide-number: true
    incremental: false 
    chalkboard: true
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
execute:
  freeze: auto
  echo: true
knitr:
  opts_chunk: 
    R.options:      
    width: 200
    
bibliography: references.bib
---

```{r setup, include=FALSE, echo=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
	fig.align = "center",
	fig.height =5,
	fig.width = 8,
	message = FALSE,
	warning = FALSE
)
```

## Announcements {.midi}

-   Lab 06 due TODAY at 11:59pm

-   HW 04 due TODAY at 11:59pm

-   Statistics experience due Tuesday, November 26

-   Project:

    -   Project meetings: November 25 and 26

        -   [Click here](https://docs.google.com/spreadsheets/d/1_TiZ84kWGs7GiTl9Sph5BkgOUScjIAlOrKyU1uAkl1I/edit?usp=sharing) to sign up (1 slot per team) by November 22

    -   Project: Draft report due + peer review December 2

    -   Round 1 submission (optional) due **December 8** at 11:59pm

-   Lecture recordings available until December 5 at 11:45am (link on sidebar of course website)

## Exam 02 format 

-   50 points total

    -   in-class: 38 points

    -   take-home: 12 points

-   In-class: 75 minutes during Thursday, December 5 lecture

-   Take-home: due Friday, December 6 at 11:59pm (grace period: can submit without late penalty until Saturday, December 7 at 11:59pm)

-   Need a note from your academic dean if you miss any part of the exam

## Exam 02 content  {.midi}

Concepts from the first half of the semester continue to apply, but the exam will focus on new content since Exam 01.

::: columns
::: {.column width="50%"}
**Multiple linear regression**

-   Maximum likelihood estimation

-   Model diagnostics

-   Multicollinearity

-   Variable transformations

-   Model comparison
:::

::: {.column width="50%"}
**Logistic regression**

-   Probabilities, odds, odds ratios

-   Maximum likelihood estimation

-   Predicted probabilities and classes

-   ROC curve and AUC

-   Inference

-   Assumptions

-   [**Not on the exam**]{.underline}: Newton-Raphson method
:::
:::

## Tips for studying  {.midi}

-   Rework derivations from assignments and lecture notes

-   Review exercises in AEs and assignments, asking "why" as you review your process and reasoning

    -   e.g., Why do we include "holding all else constant" in interpretations?

-   Understand similarities and differences between linear and logistic regression

-   Focus on understanding not memorization

-   Explain concepts / process to others

-   Ask questions in office hours

-   Review lecture recordings as needed

# Application exercise

::: appex
📋 [sta221-fa24.netlify.app/ae/ae-08-logistic-regression-review](https://sta221-fa24.netlify.app/ae/ae-08-logistic-regression-review)
:::
