---
title: "Exam 02 review"
author: "Prof. Maria Tackett"
date: "2024-12-03"
date-format: "MMM DD, YYYY"
footer: "[🔗 STA 221 - Fall 2024](https://sta221-fa24.netlify.app)"
logo: "../images/logo.png"
format: 
  revealjs:
    theme: slides.scss
    multiplex: false
    transition: fade
    slide-number: true
    incremental: false 
    chalkboard: true
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
execute:
  freeze: auto
  echo: true
knitr:
  opts_chunk: 
    R.options:      
    width: 200
    
bibliography: references.bib
---

```{r setup, include=FALSE, echo=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
	fig.align = "center",
	fig.height =5,
	fig.width = 8,
	message = FALSE,
	warning = FALSE
)
```

## Announcements {.midi}

-   Project peer review due today at 11:59pm

-   Round 1 submission (optional) due **December 8** at 11:59pm

-   Final report and GitHub repo due December 12 at 11:59pm.

-   Regular office hours end Thursday at 10am.

## Project feedback {.midi}

I would appreciate your feedback on the final project!

-   **Earn 1 point on your final project grade** by completing the feedback survey (individually scored) by **December 12.**

-   **All feedback will be anonymous.**

    -   The survey is administered by Dr. Jess Dewey in Learning Innovation. Dr. Dewey give me the names of students who have completed the survey (without responses) for the purposes of awarding extra credit.

    -   I will receive the anonymized feedback after final course grades are submitted to DukeHub.

🔗 <https://duke.qualtrics.com/jfe/form/SV_eeUQc0k5kZH8HD8> 

## Course and TA evaluations

I would appreciate your feedback about the course!

-   Course and TA evaluations are now available and are due **December 9**

-   If there is at least 80% on the course evaluations [**and**]{.underline} TA evaluations, everyone in the class will receive **1 point on their final homework average**

-   Should receive emails with access to the course and TA evaluations.

## Exam 02 format

-   50 points total

    -   in-class: 38 points

    -   take-home: 12 points

-   In-class: 75 minutes during Thursday, December 5 lecture

-   Take-home: due Friday, December 6 at 11:59pm (grace period: can submit without late penalty until Saturday, December 7 at 11:59pm)

-   Need a note from your academic dean if you miss any part of the exam

## Exam 02 content {.midi}

Concepts from the first half of the semester continue to apply, but the exam will focus on new content since Exam 01.

::: columns
::: {.column width="50%"}
**Multiple linear regression**

-   Maximum likelihood estimation

-   Model diagnostics

-   Multicollinearity

-   Variable transformations

-   Model comparison
:::

::: {.column width="50%"}
**Logistic regression**

-   Probabilities, odds, odds ratios

-   Maximum likelihood estimation

-   Predicted probabilities and classes

-   ROC curve and AUC

-   Inference

-   Assumptions

-   [**Not on the exam**]{.underline}: Newton-Raphson method
:::
:::

## Tips for studying {.midi}

-   Rework derivations from assignments and lecture notes

-   Review exercises in AEs and assignments, asking "why" as you review your process and reasoning

    -   e.g., Why do we include "holding all else constant" in interpretations?

-   Understand similarities and differences between linear and logistic regression

    -   How are interpretations for logistic regression similar to interpretations for linear regression with response $\log(y)$? How are they different?

-   Focus on understanding not memorization

-   Explain concepts / process to others

-   Ask questions in office hours

-   Review lecture recordings as needed (available until December 5 at 11:45am)

## Resources

-   Lecture notes and application exercises

-   [Lecture recordings](https://duke.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx?folderID=ccfa023a-c78c-4254-93ea-b1d80116d1dc) available until start of the exam

-   HW and lab assignments

    -   Lab 06 returned on Gradescope. [HW 04 key](https://canvas.duke.edu/courses/38867/files?preview=2247503) on Canvas until start of the exam

-   [Exam 02 practice problems](../exam-02-practice.html)

# Application exercise

::: appex
📋 [sta221-fa24.netlify.app/ae/ae-09-exam-02-review](https://sta221-fa24.netlify.app/ae/ae-09-exam-02-review)
:::
