---
title: "Lab 01" 
subtitle: "Computing + Linear algebra review"
author: "January 17, 2025"
footer: "[🔗 STA 221 - Spring 2025](https://sta221-sp25.netlify.app)"
logo: "../images/logo.png"
format: 
  revealjs:
    theme: slides.scss
    multiplex: false
    transition: fade
    slide-number: true
    incremental: false 
    chalkboard: true
execute:
  freeze: auto
  echo: true
knitr:
  opts_chunk: 
    R.options:      
    width: 200
---

## Today's lab {.midi}

**Topics**

-   Data wrangling and visualizations in R

-   Review linear algebra concepts and introduce some matrix calculus concepts

**Notes**

-   Put all responses for computing questions in your `lab-01` Quarto document. You may write any mathematical work by hand and attach it to the rendered PDF before uploading to Gradescope.

-   This lab will be graded for completion. You will receive feedback so you know what to expect in future assignments. See [Grading](https://sta221-sp25.netlify.app/labs/lab-01#grading-50-pts) for more detail

## Tips for working on lab

-   Labs will always be due **Tuesdays at 11:59pm**, but you are encouraged to complete as much as you can during the lab session.

-   One work strategy is to get through portions that you think will be most challenging during lab when a TA can help you on the spot.

-   For today's lab, start with the material you most need to review - computing or linear algebra concepts.

    -   We will begin using the linear algebra concepts in class on January 21.

## Workflow and formatting

Part of the lab grade is for “workflow and formatting” assessing the reproducible workflow and document format. This includes

-   Having at least 3 informative commit messages (practicing version control)

    -   There are markers in Lab 01 to help you incorporate version control in your workflow

-   The PDF is neatly organized document with clear exercise headings and readable code and narrative

-   The name (first and last) and date are updated at the top of the document.

## **When you’re done with lab**

-   Make sure all your final changes have been pushed to your GitHub repo

-   Submit your final PDF to Gradescope

    -   Combine the rendered Quarto document and handwritten math work into a single PDF document if needed.

    -   Access Gradescope through the course Canvas site

    -   Mark the pages associated with each exercise.

## Getting started

Ask your TA if

-   You do not have a `lab-01` repo in the GitHub course organization: [github.com/sta221-sp25](https://github.com/sta221-sp25)

-   You need help cloning the repo and starting a new RStudio project

🔗 [sta221-sp25.netlify.app/labs/lab–01.html](https://sta221-sp25.netlify.app/labs/lab–01.html)
