---
title: "Lab 05"
subtitle: "Expanding multiple linear regression"
date: "2024-11-04"
date-format: "MMM DD, YYYY"
footer: "[🔗 STA 221 - Fall 2024](https://sta221-fa24.netlify.app)"
logo: "../images/logo.png"
format: 
  revealjs:
    theme: slides.scss
    multiplex: false
    transition: fade
    slide-number: true
    incremental: false 
    chalkboard: true
    include-before: [ '<script type="text/x-mathjax-config">MathJax.Hub.Config({tex2jax: {enableAssistiveMml: false}});</script>']
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
execute:
  freeze: auto
  echo: true
knitr:
  opts_chunk: 
    R.options:      
    width: 200
bibliography: references.bib
---

# Welcome

## Goals

-   Review AE 06
-   Looking ahead - project presentations
-   Lab 05: Expanding multiple linear regression

## AE 06

::: appex
📋 [sta221-fa24.netlify.app/ae/ab-06-prob-odds](https://sta221-fa24.netlify.app/ae/ab-06-prob-odds)
:::

-   Explore the relationship between performance rating and likelihood of promotion

-   We will review Exercises 4 and 5

    -   Responses on [Google Slide](https://docs.google.com/presentation/d/1GQWIYYnJY1zRg_iukcZMnTXWlwuq9k3DoRE8GrsyuF4/edit?usp=sharing)

## Next week's lab: Project Presentations

-   5 - 8 minute presentation about your project

    -   Introduce subject matter and research question

    -   Highlights from exploratory data analysis

    -   Modeling strategy / initial modeling (if available)

    -   Any questions you'd like to get feedback on

See [project instructions](https://sta221-fa24.netlify.app/project#presentation) for more detail.

## Lab 05: Expanding multiple linear regression

This lab focuses on

-   modeling complex data using variable transformations, categorical predictors and interactions, and various model specifications.

-   evaluating model diagnostics and conditions.

🔗 <https://sta221-fa24.netlify.app/labs/lab-05>

## Reminder: Tips for working on a team

-   Do not pressure each other to finish early; use the time wisely to really learn the material and produce a quality report.

-   The labs are structured to help you learn the steps of a data analysis. Do not split up the lab among the team members; work on it together in its entirety.

-   Everyone has something to contribute! Use the lab groups as an opportunity to share ideas and learn from each other.
