{
  "hash": "f45e51b2ec54a366dba80a478cc9f182",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Logistic Regression\"\nauthor: \"Kat Husar\"\ndate: \"2024-11-07\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"[🔗 STA 221 - Fall 2024](https://sta221-fa24.netlify.app)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs:\n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: false\n    incremental: false \n    chalkboard: true\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\n---\n\n\n\n## Announcements {.midi}\n\n-   Lab 05 due TODAY 11:59pm\n\n-   Monday, November 11: Project presentations\n\n-   Looking ahead\n\n    -   Statistics experience due Tuesday, November 26\n\n## Topics\n\n-   Logistic regression for binary response variable\n\n-   Use logistic regression model to calculate predicted odds and probabilities\n\n-   Interpret the coefficients of a logistic regression model with\n\n    -   a single categorical predictor\n    -   a single quantitative predictor\n    -   multiple predictors\n\n## Computational setup\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(knitr)\nlibrary(Stat2Data) #contains data set\n\n# set default theme in ggplot2\nggplot2::theme_set(ggplot2::theme_bw())\n```\n:::\n\n\n\n# Recap\n\n## Do teenagers get 7+ hours of sleep? {.small}\n\n::: columns\n::: {.column width=\"40%\"}\nStudents in grades 9 - 12 surveyed about health risk behaviors including whether they usually get 7 or more hours of sleep.\n\n`Sleep7`\n\n1: yes\n\n0: no\n:::\n\n::: {.column width=\"60%\"}\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 446 × 6\n     Age Sleep7 Sleep           SmokeLife SmokeDaily MarijuaEver\n   <int>  <int> <fct>           <fct>     <fct>            <int>\n 1    16      1 8 hours         Yes       Yes                  1\n 2    17      0 5 hours         Yes       Yes                  1\n 3    18      0 5 hours         Yes       Yes                  1\n 4    17      1 7 hours         Yes       No                   1\n 5    15      0 4 or less hours No        No                   0\n 6    17      0 6 hours         No        No                   0\n 7    17      1 7 hours         No        No                   0\n 8    16      1 8 hours         Yes       No                   0\n 9    16      1 8 hours         No        No                   0\n10    18      0 4 or less hours Yes       Yes                  1\n# ℹ 436 more rows\n```\n\n\n:::\n:::\n\n\n:::\n:::\n\n## Let's fit a linear regression model\n\n**Outcome:** $Y$ = 1: yes, 0: no\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](19-logistic-regression_files/figure-revealjs/unnamed-chunk-3-1.png){width=960}\n:::\n:::\n\n\n\n## Let's use proportions\n\n**Outcome:** Probability of getting 7+ hours of sleep\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](19-logistic-regression_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\n\n## What happens if we zoom out?\n\n**Outcome:** Probability of getting 7+ hours of sleep\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](19-logistic-regression_files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n\n\n🛑 *This model produces predictions outside of 0 and 1.*\n\n## Let's try another model\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](19-logistic-regression_files/figure-revealjs/logistic-model-plot-1.png){width=960}\n:::\n:::\n\n\n\n*✅ This model (called a **logistic regression model**) only produces predictions between 0 and 1.*\n\n# Probabilities and odds\n\n## Binary response variable\n\n::: incremental\n-   $Y = 1: \\text{ yes}, 0: \\text{ no}$\n-   $\\pi$: **probability** that $Y=1$, i.e., $P(Y = 1)$\n-   $\\frac{\\pi}{1-\\pi}$: **odds** that $Y = 1$\n-   $\\log\\big(\\frac{\\pi}{1-\\pi}\\big)$: **log odds**\n-   Go from $\\pi$ to $\\log\\big(\\frac{\\pi}{1-\\pi}\\big)$ using the **logit transformation**\n:::\n\n## From odds to probabilities {.incremental}\n\n(1) **Logistic model**: log odds = $\\log\\big(\\frac{\\pi}{1-\\pi}\\big) = \\mathbf{X}\\boldsymbol{\\beta}$\n(2) **Odds =** $\\exp\\big\\{\\log\\big(\\frac{\\pi}{1-\\pi}\\big)\\big\\} = \\frac{\\pi}{1-\\pi}$\n(3) Combining (1) and (2) with what we saw earlier\n\n. . .\n\n$$\\text{probability} = \\pi = \\frac{\\exp\\{\\mathbf{X}\\boldsymbol{\\beta}\\}}{1 + \\exp\\{\\mathbf{X}\\boldsymbol{\\beta}\\}}$$\n\n## Sigmoid Function\n\nWe call this function relating the probability to the predictors a **sigmoid function,** $$\n\\sigma(x) = \\frac{\\exp\\{x\\}}{1 + \\exp\\{x\\}}= \\frac{1}{1+\\text{exp}\\{-x\\}}.$$\n\n## Sigmoid Function\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](19-logistic-regression_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\n\n. . .\n\n# Logistic regression\n\n## Logistic regression model\n\n**Logit form**: $$\\text{logit}(\\pi) = \\log\\big(\\frac{\\pi}{1-\\pi}\\big) = \\mathbf{X}\\boldsymbol{\\beta}$$\n\n. . .\n\n**Probability form**:\n\n$$\n\\pi = \\frac{\\exp\\{\\mathbf{X}\\boldsymbol{\\beta}\\}}{1 + \\exp\\{\\mathbf{X}\\boldsymbol{\\beta} \\}}  \n$$\n\n. . .\n\n**Logit and sigmoid link functions are inverses of each other.**\n\n::: callout-note\nMore on link functions later, if time permits\n:::\n\n## Goal\n\nWe want to use our data to estimate $\\boldsymbol{\\beta}$ (find $\\hat{\\boldsymbol{\\beta}}$) and obtain the model:\n\n$$\n\\hat\\pi = \\frac{\\exp\\{\\mathbf{X}\\hat{\\boldsymbol\\beta}\\}}{ 1 + \\exp\\{\\mathbf{X}\\hat{\\boldsymbol\\beta}\\}}\n$$\n\nIn this modeling scheme, one typically finds $\\hat{\\boldsymbol{\\beta}}$ by maximizing the **likelihood function**.\n\n## Linear Regression vs. Logistic Regression\n\n::: columns\n::: {.column width=\"50%\"}\n**Linear regression:**\n\n-   Quantitative outcome\n\n-   $y_i = x_i^\\top \\boldsymbol{\\beta} + \\epsilon_i$\n\n-   $E[Y_i] = x_i^\\top \\boldsymbol{\\beta}$\n\n-   Estimate $\\boldsymbol\\beta$\n\n-   Use $\\hat{\\boldsymbol\\beta}$ to predict $\\hat y_i$\n:::\n\n::: {.column width=\"50%\"}\n**Logistic regression:**\n\n-   Binary outcome\n\n-   $\\log\\left(\\frac{\\pi_i}{1-\\pi_i}\\right) = x_i^\\top \\boldsymbol{\\beta}$\n\n-   $E[Y_i] = \\pi_i$\n\n-   Estimate $\\boldsymbol\\beta$\n\n-   Use $\\hat{\\boldsymbol\\beta}$ to predict $\\hat \\pi_i$\n:::\n:::\n\n## Likelihood function for $\\boldsymbol{\\beta}$\n\n-   $P(Y_i = 1) = \\pi_i$. What likelihood function should we use?\n\n. . .\n\n-   $f(y_i | x_i, \\boldsymbol{\\beta}) = \\pi_i^{y_i} (1-\\pi_i)^{1-y_i}$\n\n. . .\n\n-   $Y_i$'s are independent, so\n\n$$f(y_1, \\dots, y_n) = \\prod_{i=1}^n \\pi_i^{y_i} (1-\\pi_i)^{1-y_i}$$\n\n## Likelihood\n\nThe likelihood function for $\\boldsymbol\\beta$ is\n\n$$\n\\begin{aligned}\nL&(\\boldsymbol\\beta| x_1, \\dots, x_n, y_1, \\dots, y_n) \\\\[5pt]\n &=  \\prod_{i=1}^n \\pi_i^{y_i} (1-\\pi_i)^{1-y_i} \\\\[10pt]\n\\end{aligned}\n$$ <br>\n\n. . .\n\nWe will use the log-likelihood function to find the MLEs\n\n## Log-likelihood\n\nThe log-likelihood function for $\\boldsymbol\\beta$ is\n\n$$\n\\begin{aligned}\n\\log &L(\\boldsymbol\\beta | x_1, \\dots, x_n, y_1, \\dots, y_n) \n  \\\\[8pt]\n& = \\sum_{i=1}^n\\log(\\pi_i^{y_i}(1-\\pi_i)^{1-y_i})\\\\\n&= \\sum_{i=1}^n\\left(y_i\\log (\\pi_i) + (1-y_i)\\log(1-\\pi_i)\\right)\\\\\n\\end{aligned}\n$$\n\n## Log-likelihood\n\nPlugging in $\\pi_i = \\frac{\\exp\\{x_i^\\top \\boldsymbol\\beta\\}}{1+\\exp\\{x_i^\\top \\boldsymbol\\beta\\}}$ and simplifying, we get:\n\n$$\n\\begin{aligned}\\log &L(\\boldsymbol\\beta | x_i, \\dots, x_n, y_i, \\dots, y_n) \\\\\n&= \\sum_{i=1}^n y_i x_i^\\top \\boldsymbol\\beta - \\sum_{i=1}^n \\log(1+ \\exp\\{x_i^\\top \\beta\\})\n\\end{aligned}\n$$\n\n## Finding the MLE\n\n-   Taking the derivative:\n\n$$\n\\begin{aligned}\n\\frac{\\partial \\log L}{\\partial \\boldsymbol\\beta} =\\sum_{i=1}^n y_i x_i^\\top\n&- \\sum_{i=1}^n \\frac{\\exp\\{x_i^\\top \\boldsymbol\\beta\\} x_i^\\top}{1+\\exp\\{x_i^\\top \\boldsymbol\\beta\\}}\n\\end{aligned}\n$$\n\n. . .\n\n-   If we set this to zero, there is no closed form solution.\n\n. . .\n\n-   R uses numerical approximation to find the MLE.\n\n# Example\n\n## Risk of coronary heart disease {.midi}\n\nThis data set is from an ongoing cardiovascular study on residents of the town of Framingham, Massachusetts. We want to examine the relationship between various health characteristics and the risk of having heart disease.\n\n-   `high_risk`: 1 = High risk of having heart disease in next 10 years, 0 = Not high risk of having heart disease in next 10 years\n\n-   `age`: Age at exam time (in years)\n\n-   `education`: 1 = Some High School, 2 = High School or GED, 3 = Some College or Vocational School, 4 = College\n\n\n\n::: {.cell}\n\n:::\n\n\n\n## Data: `heart_disease`\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4,135 × 3\n     age education high_risk\n   <dbl> <fct>     <fct>    \n 1    39 4         0        \n 2    46 2         0        \n 3    48 1         0        \n 4    61 3         1        \n 5    46 3         0        \n 6    43 2         0        \n 7    63 1         1        \n 8    45 2         0        \n 9    52 1         0        \n10    43 1         0        \n# ℹ 4,125 more rows\n```\n\n\n:::\n:::\n\n\n\n## High risk vs. age\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(heart_disease, aes(x = high_risk, y = age)) +\n  geom_boxplot(fill = \"steelblue\") +\n  labs(x = \"High risk - 1: yes, 0: no\",\n       y = \"Age\", \n       title = \"Age vs. High risk of heart disease\")\n```\n\n::: {.cell-output-display}\n![](19-logistic-regression_files/figure-revealjs/unnamed-chunk-10-1.png){width=960}\n:::\n:::\n\n\n\n## Let's fit the model\n\n::: small\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"1|2|3\"}\nheart_edu_age_fit <- glm(high_risk ~ age + education, \n                         data  = heart_disease, \n                         family = \"binomial\")\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -5.385|     0.308|   -17.507|   0.000|\n|age         |    0.073|     0.005|    13.385|   0.000|\n|education2  |   -0.242|     0.112|    -2.162|   0.031|\n|education3  |   -0.235|     0.134|    -1.761|   0.078|\n|education4  |   -0.020|     0.148|    -0.136|   0.892|\n\n\n:::\n:::\n\n\n\n$$\n\\begin{aligned}\n\\log\\Big(\\frac{\\hat{\\pi}}{1-\\hat{\\pi}}\\Big) =& -5.385 + 0.073 \\times \\text{age} - 0.242\\times \\text{education}_2 \\\\\n&- 0.235\\times\\text{education}_3 - 0.020 \\times\\text{education}_4\n\\end{aligned}\n$$ where $\\hat{\\pi}$ is the predicted probability of being high risk of having heart disease in the next 10 years\n:::\n\n## Interpretation in terms of log-odds\n\n::: small\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -5.385|     0.308|   -17.507|   0.000|\n|age         |    0.073|     0.005|    13.385|   0.000|\n|education2  |   -0.242|     0.112|    -2.162|   0.031|\n|education3  |   -0.235|     0.134|    -1.761|   0.078|\n|education4  |   -0.020|     0.148|    -0.136|   0.892|\n\n\n:::\n:::\n\n\n:::\n\n`education4`: The **log-odds** of being high risk for heart disease are expected to be 0.020 less for those with a college degree compared to those with some high school, **holding age constant.**\n\n. . .\n\n::: callout-warning\nWe would not use the interpretation in terms of log-odds in practice.\n:::\n\n## Interpretation in terms of log-odds\n\n::: small\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -5.385|     0.308|   -17.507|   0.000|\n|age         |    0.073|     0.005|    13.385|   0.000|\n|education2  |   -0.242|     0.112|    -2.162|   0.031|\n|education3  |   -0.235|     0.134|    -1.761|   0.078|\n|education4  |   -0.020|     0.148|    -0.136|   0.892|\n\n\n:::\n:::\n\n\n:::\n\n`age`: For each additional year in age, the log-odds of being high risk for heart disease are expected to increase by 0.073, **holding education level constant.**\n\n. . .\n\n::: callout-warning\nWe would not use the interpretation in terms of log-odds in practice.\n:::\n\n## Interpretation in terms of odds {.midi}\n\n::: small\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -5.385|     0.308|   -17.507|   0.000|\n|age         |    0.073|     0.005|    13.385|   0.000|\n|education2  |   -0.242|     0.112|    -2.162|   0.031|\n|education3  |   -0.235|     0.134|    -1.761|   0.078|\n|education4  |   -0.020|     0.148|    -0.136|   0.892|\n\n\n:::\n:::\n\n\n:::\n\n`education4`: The **odds** of being high risk for heart disease for those with a college degree are expected to be 0.98 (exp{-0.020}) **times** the odds for those with some high school, **holding age constant**.\n\n::: callout-note\nIn logistic regression with 2+ predictors, $exp\\{\\hat{\\beta}_j\\}$ is often called the **adjusted odds ratio (AOR).**\n:::\n\n## Interpretation in terms of odds {.midi}\n\n::: small\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -5.385|     0.308|   -17.507|   0.000|\n|age         |    0.073|     0.005|    13.385|   0.000|\n|education2  |   -0.242|     0.112|    -2.162|   0.031|\n|education3  |   -0.235|     0.134|    -1.761|   0.078|\n|education4  |   -0.020|     0.148|    -0.136|   0.892|\n\n\n:::\n:::\n\n\n:::\n\n`age`: For each additional year in age, the odds being high risk for heart disease are expected to multiply by a factor of 1.08 (`exp(0.073)`), **holding education level constant**.\n\n**Alternate interpretation:** For each additional year in age, the odds of being high risk for heart disease are expected to increase by 8%.\n\n::: callout-note\nIn logistic regression with 2+ predictors, $exp\\{\\hat{\\beta}_j\\}$ is often called the **adjusted odds ratio (AOR).**\n:::\n\n# Generalized Linear Models\n\n## Introduction to GLMs\n\n::: incremental\n-   Wider class of models.\n-   Response variable does not have to be continuous and/or normal.\n-   Variance does not have to be constant\n-   Still need to specify distribution of outcome variable (randomness).\n-   Does not require a linear relationship between response and explanatory variable. Instead, assumes linear relationship between the transformed expected response (ex. $\\text{logit}(\\pi_i)$) and predictors.\n:::\n\n## Generalization of Linear Model\n\n::: midi\n**Linear model**\n\n$E[Y_i] = \\mu_i = x_i^\\top\\boldsymbol\\beta$.\n\n$Y_i \\overset{ind}{\\sim} N(\\mu_i, \\sigma^2)$.\n:::\n\n. . .\n\n::: midi\n**GLM**\n\n$g\\left(E[Y_i]\\right) = g(\\mu_i)  = x_i^\\top \\beta$. Alternatively, $\\mu_i \\sim g^{-1}(x_i^\\top \\beta)$.\n\n$Y_i \\overset{ind}{\\sim} f(\\mu_i)$.\n:::\n\n. . .\n\n::: callout-note\nWe call $g$ a link function\n:::\n\n## Examples of link functions\n\n**Linear regression**\n\n$g(\\mu_i) = \\mu_i$ and $Y_i\\sim N(\\mu_i,\\sigma^2)$.\n\n. . .\n\n**Logistic regression**\n\n$g(\\pi_i) = \\text{logit}(\\pi_i)$ (note, $E[Y_i] = \\pi_i$). $Y_i \\sim \\text{Bernoulli}(\\pi_i)$. Alternatively, $\\pi_i = \\sigma(x_i^\\top\\boldsymbol\\beta)$ where $\\sigma$ is the sigmoid function.\n\n. . .\n\n**Probit model**\n\n$\\pi_i = \\Phi(x_i^\\top\\boldsymbol\\beta)$, where $\\Phi$ is the cdf of standard normal. $Y_i \\sim \\text{Bernoulli}(\\pi_i)$. $g(\\pi_i) = \\Phi^{-1}(\\pi_i)$ is called a probit link.\n\n# Prediction\n\n## Predicted log odds {.midi}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheart_disease_aug = \n  augment(heart_edu_age_fit) \nheart_disease_aug|> select(.fitted, .resid)|>\n  head(6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  .fitted .resid\n    <dbl>  <dbl>\n1   -2.55 -0.388\n2   -2.26 -0.446\n3   -1.87 -0.536\n4   -1.15  1.69 \n5   -2.25 -0.448\n6   -2.48 -0.402\n```\n\n\n:::\n:::\n\n\n\n. . .\n\n**For observation 1**\n\n$$\\text{predicted odds} = \\hat{\\omega} = \\frac{\\hat{\\pi}}{1-\\hat{\\pi}} = \\exp\\{-2.548\\} = 0.078$$\n\n## Predicted probabilities {.midi}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheart_disease_aug$predicted_prob <- \n  predict.glm(heart_edu_age_fit, heart_disease, type = \"response\")\nheart_disease_aug|>\n  select(.fitted,predicted_prob) |>\n  head(6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  .fitted predicted_prob\n    <dbl>          <dbl>\n1   -2.55         0.0726\n2   -2.26         0.0948\n3   -1.87         0.134 \n4   -1.15         0.240 \n5   -2.25         0.0954\n6   -2.48         0.0775\n```\n\n\n:::\n:::\n\n\n\n. . .\n\n**For observation 1**\n\n$$\\text{predicted probability} = \\hat{\\pi} = \\frac{\\exp\\{-2.548\\}}{1 + \\exp\\{-2.548\\}} = 0.073$$\n\n## Predicted classes\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert probabilities to binary predictions (0 or 1)\nheart_disease_aug <- heart_disease_aug |>\n  mutate(predicted_class =  ifelse(predicted_prob > 0.5, 1, 0))\nheart_disease_aug |>\n  select(predicted_prob, predicted_class) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4,135 × 2\n   predicted_prob predicted_class\n            <dbl>           <dbl>\n 1         0.0726               0\n 2         0.0948               0\n 3         0.134                0\n 4         0.240                0\n 5         0.0954               0\n 6         0.0775               0\n 7         0.317                0\n 8         0.0887               0\n 9         0.172                0\n10         0.0967               0\n# ℹ 4,125 more rows\n```\n\n\n:::\n:::\n\n\n\n## Observed vs. predicted\n\n::: question\nWhat does the following table show?\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheart_disease_aug|>\n  count(high_risk, predicted_class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  high_risk predicted_class     n\n  <fct>               <dbl> <int>\n1 0                       0  3507\n2 1                       0   628\n```\n\n\n:::\n:::\n\n\n\n. . .\n\n::: question\nThe `predicted_class` is the class with the probability of occurring higher than 0.5. What is a limitation to using this method to determine the predicted class?\n:::\n\n## Recap\n\n-   Reviewed the relationship between odds and probabilities\n\n-   Introduced logistic regression for binary response variable\n\n-   Interpreted the coefficients of a logistic regression model with multiple predictors\n\n-   Introduced generalized linear model\n",
    "supporting": [
      "19-logistic-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}