{
  "hash": "da4e85b0fc699af6216f5d07f8925230",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Probabilites, odds, odds ratios\"\nauthor: \"Prof. Maria Tackett\"\ndate: \"2024-10-31\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"[🔗 STA 221 - Fall 2024](https://sta221-fa24.netlify.app)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs:\n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: true\n    incremental: false \n    chalkboard: true\n    include-before: [ '<script type=\"text/x-mathjax-config\">MathJax.Hub.Config({tex2jax: {enableAssistiveMml: false}});</script>']\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nfilters:\n  - parse-latex\nbibliography: references.bib\n---\n\n\n\n\n\n## Announcements {.midi}\n\n-   HW 03 due TODAY 11:59pm\n\n-   Project: Exploratory data analysis due TODAY at 11:59pm\n\n-   Tuesday, November 5: Wellness Day (no lecture)\n\n-   Looking ahead\n\n    -   Project presentations November 11\n\n    -   Statistics experience due Tuesday, November 26\n\n## Topics\n\n-   Logistic regression for binary response variable\n\n-   Relationship between odds and probabilities\n\n-   Odds ratios and connection to logistic model\n\n## Computational setup\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(knitr)\nlibrary(Stat2Data) #contains data set\n\n# set default theme in ggplot2\nggplot2::theme_set(ggplot2::theme_bw())\n```\n:::\n\n\n\n# Predicting categorical outcomes\n\n## Types of outcome variables\n\n**Quantitative outcome variable**:\n\n-   Sales price of a house in Duke Forest\n-   **Model**: Expected sales price given the number of bedrooms, lot size, etc.\n\n. . .\n\n**Categorical outcome variable**:\n\n-   Indicator of being high risk of getting coronary heart disease in the next 10 years\n-   **Model**: Probability an adult is high risk of heart disease in the next 10 years given their age, total cholesterol, etc.\n\n## Models for categorical outcomes\n\n::: columns\n::: {.column width=\"50%\"}\n**Logistic regression**\n\n2 Outcomes\n\n1: Yes, 0: No\n:::\n\n::: {.column width=\"50%\"}\n**Multinomial logistic regression (in STA 310)**\n\n3+ Outcomes\n\n1: Democrat, 2: Republican, 3: Independent\n:::\n:::\n\n## Do teenagers get 7+ hours of sleep? {.smaller}\n\n::: columns\n::: {.column width=\"40%\"}\nStudents in grades 9 - 12 surveyed about health risk behaviors including whether they usually get 7 or more hours of sleep.\n\n`Sleep7`\n\n1: yes\n\n0: no\n:::\n\n::: {.column width=\"60%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 446 × 6\n     Age Sleep7 Sleep           SmokeLife SmokeDaily MarijuaEver\n   <int>  <int> <fct>           <fct>     <fct>            <int>\n 1    16      1 8 hours         Yes       Yes                  1\n 2    17      0 5 hours         Yes       Yes                  1\n 3    18      0 5 hours         Yes       Yes                  1\n 4    17      1 7 hours         Yes       No                   1\n 5    15      0 4 or less hours No        No                   0\n 6    17      0 6 hours         No        No                   0\n 7    17      1 7 hours         No        No                   0\n 8    16      1 8 hours         Yes       No                   0\n 9    16      1 8 hours         No        No                   0\n10    18      0 4 or less hours Yes       Yes                  1\n# ℹ 436 more rows\n```\n\n\n:::\n:::\n\n\n:::\n:::\n\n## Plot the data\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(sleep, aes(x = Age, y = Sleep7)) +\n  geom_point() + \n  labs(y = \"Getting 7+ hours of sleep\")\n```\n\n::: {.cell-output-display}\n![](18-prob-odds_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\n## Let's fit a linear regression model\n\n**Outcome:** $Y$ = 1: yes, 0: no\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](18-prob-odds_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\n## Let's use proportions\n\n**Outcome:** Probability of getting 7+ hours of sleep\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](18-prob-odds_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\n## What happens if we zoom out?\n\n**Outcome:** Probability of getting 7+ hours of sleep\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](18-prob-odds_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\n🛑 *This model produces predictions outside of 0 and 1.*\n\n## Let's try another model\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](18-prob-odds_files/figure-revealjs/logistic-model-plot-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\n*✅ This model (called a **logistic regression model**) only produces predictions between 0 and 1.*\n\n## The code\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(sleep_age, aes(x = Age, y = prop)) +\n  geom_point() + \n  geom_hline(yintercept = c(0,1), lty = 2) + \n  stat_smooth(method =\"glm\", method.args = list(family = \"binomial\"), \n              fullrange = TRUE, se = FALSE) +\n  labs(y = \"P(7+ hours of sleep)\") +\n  xlim(1, 40) +\n  ylim(-0.5, 1.5)\n```\n:::\n\n\n\n## Different types of models\n\n| Method                          | Outcome      | Model                                                           |\n|---------------------------------|--------------|-----------------------------------------------------------------|\n| Linear regression               | Quantitative | $y_i = \\beta_0 + \\beta_1~ x_i$                                  |\n| Linear regression (transform Y) | Quantitative | $\\log(y_i) = \\beta_0 + \\beta_1~ x_i$                            |\n| Logistic regression             | Binary       | $\\log\\big(\\frac{\\pi_i}{1-\\pi_i}\\big) = \\beta_0 + \\beta_1 ~ x_i$ |\n\n## Linear vs. logistic regression\n\n::: question\nState whether a linear regression model or logistic regression model is more appropriate for each scenario.\n\n1.  Use age and education to predict if a randomly selected person will vote in the next election.\n\n2.  Use budget and run time (in minutes) to predict a movie's total revenue.\n\n3.  Use age and sex to calculate the probability a randomly selected adult will visit Duke Health in the next year.\n:::\n\n# Probabilities and odds\n\n## Binary response variable\n\n::: incremental\n-   $Y = 1: \\text{ yes}, 0: \\text{ no}$\n-   $\\pi$: **probability** that $Y=1$, i.e., $P(Y = 1)$\n-   $\\frac{\\pi}{1-\\pi}$: **odds** that $Y = 1$\n-   $\\log\\big(\\frac{\\pi}{1-\\pi}\\big)$: **log odds**\n-   Go from $\\pi$ to $\\log\\big(\\frac{\\pi}{1-\\pi}\\big)$ using the **logit transformation**\n:::\n\n## Odds\n\n::: incremental\nSuppose there is a **70% chance** it will rain tomorrow\n\n-   Probability it will rain is $\\mathbf{p = 0.7}$\n-   Probability it won't rain is $\\mathbf{1 - p = 0.3}$\n-   Odds it will rain are **7 to 3**, **7:3**, $\\mathbf{\\frac{0.7}{0.3} \\approx 2.33}$\n:::\n\n## Are teenagers getting enough sleep?\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsleep |>\n  count(Sleep7) |>\n  mutate(p = round(n / sum(n), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  Sleep7     n     p\n   <int> <int> <dbl>\n1      0   150 0.336\n2      1   296 0.664\n```\n\n\n:::\n:::\n\n\n\n. . .\n\n$P(\\text{7+ hours of sleep}) = P(Y = 1) = p = 0.664$\n\n. . .\n\n$P(\\text{< 7 hours of sleep}) = P(Y = 0) = 1 - p = 0.336$\n\n. . .\n\n$P(\\text{odds of 7+ hours of sleep}) = \\frac{0.664}{0.336} = 1.976$\n\n## From odds to probabilities\n\n::: columns\n::: {.column width=\"50%\"}\n**odds**\n\n$$\\omega = \\frac{\\pi}{1-\\pi}$$\n:::\n\n::: {.column width=\"50%\"}\n**probability**\n\n$$\\pi = \\frac{\\omega}{1 + \\omega}$$\n:::\n:::\n\n# Odds ratios\n\n## Risk of coronary heart disease {.midi}\n\nThis data set is from an ongoing cardiovascular study on residents of the town of Framingham, Massachusetts. We want to examine the relationship between various health characteristics and the risk of having heart disease. These notes focus on the following variables:\n\n-   `high_risk`:\n\n    -   1: High risk of having heart disease in next 10 years\n    -   0: Not high risk of having heart disease in next 10 year\n\n-   `education`: 1 = Some High School, 2 = High School or GED, 3 = Some College or Vocational School, 4 = College\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n## High risk vs. education\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|Education                         | High risk| Not high risk|\n|:---------------------------------|---------:|-------------:|\n|Some high school                  |       323|          1397|\n|High school or GED                |       147|          1106|\n|Some college or vocational school |        88|           601|\n|College                           |        70|           403|\n\n\n:::\n:::\n\n\n\n## Compare the odds for two groups {.midi}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|Education                         | High risk| Not high risk|\n|:---------------------------------|---------:|-------------:|\n|Some high school                  |       323|          1397|\n|High school or GED                |       147|          1106|\n|Some college or vocational school |        88|           601|\n|College                           |        70|           403|\n\n\n:::\n:::\n\n\n\n. . .\n\n-   We want to compare the risk of heart disease for those with a High School diploma/GED and those with a college degree.\n\n-   We'll use the **odds** to compare the two groups\n\n$$\n\\text{odds} = \\frac{P(\\text{success})}{P(\\text{failure})} = \\frac{\\text{# of successes}}{\\text{# of failures}}\n$$\n\n## Compare the odds for two groups {.midi}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|Education                         | High risk| Not high risk|\n|:---------------------------------|---------:|-------------:|\n|Some high school                  |       323|          1397|\n|High school or GED                |       147|          1106|\n|Some college or vocational school |        88|           601|\n|College                           |        70|           403|\n\n\n:::\n:::\n\n\n\n-   Odds of being high risk for the **High school or GED** group: $\\frac{147}{1106} = 0.133$\n\n-   Odds of being high risk for the **College** group: $\\frac{70}{403} = 0.174$\n\n-   Based on this, we see those with a college degree had higher odds of being high risk for heart disease than those with a high school diploma or GED.\n\n## Odds ratio (OR) {.midi}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|Education                         | High risk| Not high risk|\n|:---------------------------------|---------:|-------------:|\n|Some high school                  |       323|          1397|\n|High school or GED                |       147|          1106|\n|Some college or vocational school |        88|           601|\n|College                           |        70|           403|\n\n\n:::\n:::\n\n\n\nLet's summarize the relationship between the two groups. To do so, we'll use the **odds ratio (OR)**.\n\n$$\nOR = \\frac{\\text{odds}_1}{\\text{odds}_2} = \\frac{\\omega_1}{\\omega_2}\n$$\n\n## OR: College vs. High school or GED {.midi}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|Education                         | High risk| Not high risk|\n|:---------------------------------|---------:|-------------:|\n|Some high school                  |       323|          1397|\n|High school or GED                |       147|          1106|\n|Some college or vocational school |        88|           601|\n|College                           |        70|           403|\n\n\n:::\n:::\n\n\n\n$$OR = \\frac{\\text{odds}_{College}}{\\text{odds}_{HS}} = \\frac{0.174}{0.133} = \\mathbf{1.308}$$\n\n. . .\n\nThe odds of being high risk for heart disease are 1.30 times higher for those with a college degree than those with a high school diploma or GED.\n\n## OR: College vs. Some high school {.midi}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|Education                         | High risk| Not high risk|\n|:---------------------------------|---------:|-------------:|\n|Some high school                  |       323|          1397|\n|High school or GED                |       147|          1106|\n|Some college or vocational school |        88|           601|\n|College                           |        70|           403|\n\n\n:::\n:::\n\n\n\n$$OR = \\frac{\\text{odds}_{College}}{\\text{odds}_{Some HS}} = \\frac{70/403}{323/1397} = 0.751$$\n\n. . .\n\nThe odds of being high risk for having heart disease for those with a college degree are 0.751 times the odds of being high risk for heart disease for those with some high school.\n\n## More natural interpretation\n\n-   It's more natural to interpret the odds ratio with a statement with the odds ratio greater than 1.\n\n-   The odds of being high risk for heart disease are 1.33 times higher for those with some high school than those with a college degree.\n\n## Making the table 1\n\nFirst, rename the levels of the categorical variables:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_disease <- heart_disease |>\n  mutate(\n    high_risk_names = if_else(high_risk == \"1\", \"High risk\", \"Not high risk\"),\n    education_names = case_when(\n      education == \"1\" ~ \"Some high school\",\n      education == \"2\" ~ \"High school or GED\",\n      education == \"3\" ~ \"Some college or vocational school\",\n      education == \"4\" ~ \"College\"\n    ),\n    education_names = fct_relevel(education_names, \"Some high school\", \"High school or GED\", \"Some college or vocational school\", \"College\")\n  )\n```\n:::\n\n\n\n## Making the table 2\n\nThen, make the table:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_disease |>\n  count(education_names, high_risk_names) |>\n  pivot_wider(names_from = high_risk_names, values_from = n) |>\n  kable(col.names = c(\"Education\", \"High risk\", \"Not high risk\"))\n```\n:::\n\n\n\n## Deeper look into the code\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_disease |>\n  count(education_names, high_risk_names)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 3\n  education_names                   high_risk_names     n\n  <fct>                             <chr>           <int>\n1 Some high school                  High risk         323\n2 Some high school                  Not high risk    1397\n3 High school or GED                High risk         147\n4 High school or GED                Not high risk    1106\n5 Some college or vocational school High risk          88\n6 Some college or vocational school Not high risk     601\n7 College                           High risk          70\n8 College                           Not high risk     403\n```\n\n\n:::\n:::\n\n\n\n## Deeper look into the code\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"3\"}\nheart_disease |>\n  count(education_names, high_risk_names) |>\n  pivot_wider(names_from = high_risk_names, values_from = n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  education_names                   `High risk` `Not high risk`\n  <fct>                                   <int>           <int>\n1 Some high school                          323            1397\n2 High school or GED                        147            1106\n3 Some college or vocational school          88             601\n4 College                                    70             403\n```\n\n\n:::\n:::\n\n\n\n## Deeper look into the code\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"4\"}\nheart_disease |>\n  count(education_names, high_risk_names) |>\n  pivot_wider(names_from = high_risk_names, values_from = n) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|education_names                   | High risk| Not high risk|\n|:---------------------------------|---------:|-------------:|\n|Some high school                  |       323|          1397|\n|High school or GED                |       147|          1106|\n|Some college or vocational school |        88|           601|\n|College                           |        70|           403|\n\n\n:::\n:::\n\n\n\n## Deeper look into the code\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"4\"}\nheart_disease |>\n  count(education_names, high_risk_names) |>\n  pivot_wider(names_from = high_risk_names, values_from = n) |>\n  kable(col.names = c(\"Education\", \"High risk\", \"Not high risk\"))\n```\n\n::: {.cell-output-display}\n\n\n|Education                         | High risk| Not high risk|\n|:---------------------------------|---------:|-------------:|\n|Some high school                  |       323|          1397|\n|High school or GED                |       147|          1106|\n|Some college or vocational school |        88|           601|\n|College                           |        70|           403|\n\n\n:::\n:::\n\n\n\n# Application exercise\n\n::: appex\n📋 <https://sta221-fa24.netlify.app/ae/ae-06-prob-odds.html>\n:::\n\nIf your group is selected, [click here](https://docs.google.com/presentation/d/1GQWIYYnJY1zRg_iukcZMnTXWlwuq9k3DoRE8GrsyuF4/edit?usp=sharing) to add your response to the Google Slide.\n\n## Recap\n\n-   Introduced logistic regression for binary response variable\n\n-   Showed the relationship between odds and probabilities\n\n-   Introduced odds ratios and their connection to logistic model\n",
    "supporting": [
      "18-prob-odds_files/figure-revealjs"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}