---
title: "Lab 04: Maximum Likelihood Estimation"
format: html
---

::: callout-important
## Date due

-   Add dates
-   Add dates
:::

# Maximum Likelihood Estimation

In this lab, we will see how a standard simple linear regression analysis can be interpreted as a maximum likelihood estimation procedure.

## Packages

For today's lab, we will be using the following packages.

```{r packages}
#| message: false
library(tidyverse)
library(palmerpenguins)
```

## Data

\[Add introduction about the penguins data set\]

## Exercises

**The goal is to use bill length and island to understand variability in bill depth.**

### Exercise 1

Visualize the relationship between the response variable and each of the predictors. Use the visualizations to describe the relationship between the response and each predictor.

### Exercise 2

We wish to fit a model using the bill length, island, and the interaction between the two variables to understand variability in the bill depth.

-   Write the form of the statistical (population-level) model in matrix form.

-   Write the dimensions for $\mathbf{y}, \mathbf{X}, \boldsymbol{\beta}, \sigma^2_{\epsilon}$ specific for this problem.

### Exercise 3

Consider the regression model described in **Exercise 2**.

-   Write down the form of the likelihood function $L(\boldsymbol{\beta}, \sigma^2_{\epsilon} | \mathbf{y}, \mathbf{X})$ in matrix form.

-   Describe how each of the four model assumptions is necessary for the likelihood function.

### Exercise 4

Briefly explain how maximum likelihood estimation for the likelihood function in the previous exercise is related to least-squares estimation for the model in Exercise 2.

### Exercise 5

For the next few exercises, we will compare the results of the maximum likelihood and least-squares procedures.

-   Fit the regression model corresponding to the statistical model in Exercise 2. Neatly display the results using three digits.

-   Describe the estimated effect of bill length on bill depth, including whether there is statistical evidence of a difference in the effect by island.

### Exercise 6

-   Use matrix/vector operations to compute the maximum likelihood estimators $\tilde{\beta}$ for the model in Exercise 2.

-   How do these estimators compare to the least-squares estimators in the previous exercise?

### Exercise 7

The maximum likelihood estimation procedure also produces an estimator for the variance about the regression line, $\sigma^2_\epsilon$, which we can write as

$$
\tilde{\sigma}^2_{\epsilon} = \frac{1}{n} \mathbf{e}^T\mathbf{e}
$$

We know that the maximum likelihood estimate and least-squares estimates for $\sigma^2_{\epsilon}$ are not equal. Additionally, the least-squares estimator $\hat{\sigma}^2_{\epsilon}$ is unbiased. We want to find a scaling factor $c$ such that the maximum likelihood estimator is unbiased.

Using the data and regression estimates from `penguins`, compute both estimators for $\sigma_{\epsilon}^2$, and then find $c$ by solving the equation $$ \hat\sigma^2_{\epsilon} = c \cdot \tilde\sigma^2_{\epsilon} $$ You can do this last step either computationally or algebraically.

### Exercise 8

Now we will look into the last property of the maximum likelihood estimator for $\boldsymbol{\beta}$, and thus of least-squares estimates - their **asymptotic normality**.

In words, this property says that, when the number of samples $n$ is large compared to the number of predictors $p$, the ML estimator $\hat{\boldsymbol\beta}$ follows a multivariate normal distribution $\mathsf{N}\big(\boldsymbol\beta, \sigma_\epsilon^2 (\mathbf{X}^\top\mathbf{X})^{-1}\big)$. Let's use this to construct an approximate confidence interval for $\beta_j$, the coefficient for `islandDream`.

Use $\tilde{\sigma}^2_{\epsilon}$, the maximum likelihood estimator, to compute the approximate confidence interval for $\beta_j$ . The approximate confidence interval may be computed as

$\tilde{\beta}_j\pm 2 \times SE(\tilde{\beta}_j)$

### Exercise 9

Compute the exact (based on the $t$-distribution) confidence interval for $\beta_1$, then compare the center and width of the this exact interval with the one you computed in **Exercise 8**. Do they differ? By how much? Which one is wider, indicating more uncertainty?

### Exercise 10

To wrap up, we have seen that both the OLS and the ML procedures for linear regression produce the same coefficient estimates, but lead to different estimators for the variance $\sigma_\epsilon^2$ and allow for different types of uncertainty quantification.

Based on the work in this lab, do you think performing inference based on either method would have changed your conclusions about the difference (or lack thereof) in the relationship between bill depth and bill length by island?

# Submission 

# Grading
