{
  "hash": "7d6394041ec7e8cce67b9504ed41cb33",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"AE 04: Exam 01 Review\"\ndate: \"October 3, 2024\"\neditor: visual\n---\n\n\n\n::: callout-important\nGo to the course GitHub organization and locate your ae-04 repo to get started.\n\nRender, commit, and push your responses to GitHub by the end of class to submit your AE.\n:::\n\n## Packages\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(knitr)\nlibrary(patchwork)\n```\n:::\n\n\n\n## Restaurant tips\n\n**What factors are associated with the amount customers tip at a restaurant?** To answer this question, we will use data collected in 2011 by a student at St. Olaf who worked at a local restaurant.[^1]\n\n[^1]: Dahlquist, Samantha, and Jin Dong. 2011. \"The Effects of Credit Cards on Tipping.\" Project for Statistics 212-Statistics for the Sciences, St. Olaf College.\n\nThe variables we'll focus on for this analysis are\n\n-   `Tip`: amount of the tip\n-   `Party`: number of people in the party\n-   `Age`: Age of the payer\n\nView the data set to see the remaining variables.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntips <- read_csv(\"data/tip-data.csv\")\n```\n:::\n\n\n\n## Exploratory data analysis\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(data = tips, aes(x = Tip)) + \n  geom_histogram(color = \"white\", binwidth = 2) +\n  labs(x = \"Tips ($)\",\n       title = \"Tips at local restaurant\")\n\np2 <- ggplot(data = tips, aes(x = Party)) + \n  geom_histogram(color = \"white\") +\n  labs(x = \"Party\",\n       title = \"Number of diners in party\") +\n  xlim(c(0, 7))\n\np3 <- ggplot(data = tips, aes(x = Age)) + \n  geom_bar(color = \"white\") +\n  labs(x = \"\",\n       title = \"Age of Payer\") \n\np1 / (p2 + p3)\n```\n\n::: {.cell-output-display}\n![](ae-04-exam-01-review_files/figure-html/univariate-eda-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\np4 <- ggplot(data = tips, aes(x = Party, y = Tip)) + \n  geom_jitter() + \n  labs(x = \"Number of diners in party\", \n       y = \"Tips ($)\",\n       title = \"Tips vs. Party\")\n\np5 <- ggplot(data = tips, aes(x = Age, y = Tip)) + \n  geom_boxplot() + \n  labs(x = \"Age of payer\", \n       y = \"Tips ($)\",\n       title = \"Tips vs. Age\")\n\np4 + p5\n```\n\n::: {.cell-output-display}\n![](ae-04-exam-01-review_files/figure-html/bivariate-eda-1.png){width=672}\n:::\n:::\n\n\n\n**We will use the number of diners in the party and age of the payer to understand variability in the tips.**\n\n## Exercise 1\n\nWe will start with the main effects model.\n\na.  How many indicator variables for `Age` can we create from the data?\nb.  How many indicator variables for `Age` will be in the regression model?\nc.  Are the responses to parts a and b equal? If not, explain why not.\nd.  Which of the following is true for this model? Select all that apply.\n    i.  The intercepts are the same for every level of `Age`.\n    ii. The intercepts differ by `Age`.\n    iii. The effect of `Party` is the same for every level of `Age`.\n    iv. The effect of `Party` differs by `Age`.\n\n## Exercise 2\n\na.  What is the dimension of the design matrix $\\mathbf{X}$ for the main effects model?\n\nb.  Calculate the coefficient estimates $\\hat{\\boldsymbol{\\beta}}$ directly from the data.\n\nc.  Write the equation of the estimated regression model.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# add code here \n```\n:::\n\n\n\n## Exercise 3\n\nCompute the following directly from the data:\n\na.  The regression standard error $\\hat{\\sigma}_{\\epsilon}$ . Interpret this value in the context of the data.\nb.  $R^2$. Interpret this value in the context of the data.\nc.  $RMSE$. Interpret this value in the context of the data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# add code here\n```\n:::\n\n\n\n## Exercise 4\n\nYou decide to add an interaction effect between `Age` and `Party` to the model and fit a model of the following form:\n\n$$\n\\hat{Tip}_i = \\beta_0 + \\beta_1Party_i + \\beta_2SenCit_i + \\beta_3Yadult_i + \\beta_4Party_i \\times SenCit_i + \\beta_5 Party_i \\times Yadult_i \n$$\n\na.  Which of the following is true for this model? Select all that apply.\n    i.  The intercepts are the same for every level of `Age`.\n    ii. The intercepts differ by `Age`.\n    iii. The effect of `Party` is the same for every level of `Age`.\n    iv. The effect of `Party` differs by `Age`.\nb.  By how much does the intercept for tables with young adult payers differ from tables with middle age payers?\nc.  Write the equation of the model for tables in which the payer is a senior citizen.\nd.  Suppose you wish to test the hypotheses: $H_0: \\beta_5 = 0 \\text{ vs. }H_a: \\beta_5 \\neq 0$ . State what is being tested in terms of the effect of `Party`.\n\n## Exercise 5\n\nThe output for the model with the interaction term and 90% confidence intervals for the coefficients is shown below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntip_int_fit <- lm(Tip ~ Party + Age + Party * Age, data = tips)\ntidy(tip_int_fit, conf.int = TRUE, conf.level = 0.9) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term            | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:---------------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept)     |    0.604|     0.504|     1.199|   0.232|   -0.229|     1.438|\n|Party           |    1.924|     0.169|    11.359|   0.000|    1.644|     2.204|\n|AgeSenCit       |    1.033|     0.784|     1.317|   0.190|   -0.265|     2.330|\n|AgeYadult       |   -1.203|     0.928|    -1.297|   0.197|   -2.739|     0.332|\n|Party:AgeSenCit |   -0.259|     0.262|    -0.986|   0.325|   -0.692|     0.175|\n|Party:AgeYadult |    0.199|     0.504|     0.395|   0.693|   -0.635|     1.034|\n\n\n:::\n:::\n\n\n\na.  What does 0.784, the standard error of `AgeSenCit` mean in the context of the data?\nb.  What does 1.317, the test statistic for `AgeSenCit` mean in the context of the data?\nc.  What does the p-value 0.190 mean in the context of the data?\nd.  The 90% confidence interval corresponds to what $\\alpha$-level?\ne.  What is your conclusion about the effect of `AgeSenCit`?\n\n## Exercise 6\n\nThe following are general questions about regression. They are not specific to the tips data set.\n\na.  What does it mean for an estimator to be the \"least-squares\" estimator?\n\nb.  Consider the following derivation of $Var(\\hat{\\boldsymbol{\\beta}})$ , the variance of the least-squares estimator:\n\n    $$\n    \\begin{aligned}\n    Var(\\hat{\\boldsymbol{\\beta}}) & = E[(\\hat{\\boldsymbol{\\beta}} - \\boldsymbol{\\beta})(\\hat{\\boldsymbol{\\beta}} - \\boldsymbol{\\beta})^T] \\\\\n    & = E[((\\mathbf{X}^T\\mathbf{X})^{-1}\\mathbf{X}^T\\boldsymbol{\\epsilon})((\\mathbf{X}^T\\mathbf{X})^{-1}\\mathbf{X}^T\\boldsymbol{\\epsilon})^T] \\\\\n    & = (\\mathbf{X}^T\\mathbf{X})^{-1}\\mathbf{X}^TE(\\boldsymbol{\\epsilon}\\boldsymbol{\\epsilon}^T)\\mathbf{X}(\\mathbf{X}^T\\mathbf{X})^{-1} \\\\\n    & = \\sigma^2(\\mathbf{X}^T\\mathbf{X})^{-1}\n    \\end{aligned}\n    $$\n\nExplain how to go from Line 1 to Line 2.\n\nc.  What assumptions are used to go from Line 3 to Line 4?\n\n::: callout-important\n# Submission\n\nTo submit the AE:\n\nRender the document to produce the PDF with all of your work from today's class.\n\nPush all your work to your AE repo on GitHub. You're done! 🎉\n:::\n",
    "supporting": [
      "ae-04-exam-01-review_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}